services:
  kong:
    image: kong:3.5
    container_name: kong
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /kong/kong.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    volumes:
      - ./gateway/kong.yaml:/kong/kong.yaml:ro,z
    user: "0:0"
    depends_on:
      - cache-service
      - customer-service
      - order-service
      - payment-service
      - chat-service
      - file-service
  cache-service:
    build: ./services/cache
    container_name: cache-service
    ports:
      - "3001:3000"
    depends_on:
      - redis
  customer-service:
    build: ./services/customer
    container_name: customer-service
    ports:
      - "3002:3000"
    depends_on:
      - mongo
  order-service:
    build: ./services/order
    container_name: order-service
    ports:
      - "3003:3000"
    depends_on:
      - mongo
  payment-service:
    build: ./services/payment
    container_name: payment-service
    ports:
      - "3004:3000"
  chat-service:
    build: ./services/chat
    container_name: chat-service
    ports:
      - "3005:3000"
  file-service:
    build: ./services/file
    container_name: file-service
    ports:
      - "3006:3000"
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  mongo_data: 